version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cloud
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password # Set authentication plugin
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: